include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    use_build_context_synchronously: ignore
  exclude:
    - '**.freezed.dart'
    - '**.g.dart'
    - '**.gr.dart'
    - '**/generated_plugin_registrant.dart'
    # - 'cloned_apis/mustachex/**' 
    - 'cloned_apis/mason/**' 
 
linter: 
  rules: 