name: mustachehub
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

dependency_overrides: 
  uuid: ^4.3.3
  mustachex: 
    path: cloned_apis/mustachex  

environment:
  sdk: '>=3.2.3 <4.0.0' 
dependencies:
  flutter:
    sdk: flutter 
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  text_analyser: 
    path: packages/text_analyser
  uuid: ^4.3.3
  freezed_annotation: ^2.4.1
  lottie: ^2.7.0
  font_awesome_flutter: ^10.6.0
  bloc: ^8.1.2 
  flutter_bloc: ^8.1.3
  replay_bloc: ^0.2.5
  enchanted_regex: ^1.0.7
  hydrated_bloc: ^9.1.3 
  go_router: ^13.0.1
  google_fonts: ^6.2.1
  enchanted_collection: 1.3.0
  simple_platform: ^1.0.1
  image_network: ^2.5.4+1
  image_picker: ^1.0.4
  image_picker_for_web: ^3.0.1
  flutter_animate:
  url_launcher: ^6.2.4
  fluttertoast: ^8.2.4
  dart_debouncer: ^1.1.0
  dotted_border: ^2.1.0
  cursor_autocomplete_options: ^1.5.0
  path_provider: ^2.1.2
  media_query_core:
    path: packages/media_query_core
  mustache_hub_core:
    path: packages/mustache_hub_core
  commom_states:
    path: packages/commom_states

  # Fork api's
  mustachex:
  mason: 
    path: cloned_apis/mason

  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  firebase_storage: ^11.6.0
  cloud_firestore: ^4.15.9
  flex_color_scheme: ^7.3.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"
  build_runner: ^2.3.3 
  json_serializable: ^6.7.1
  freezed: ^2.3.2

flutter_launcher_icons:
  image_path: "assets/visual_identity/raw_logo.PNG"
  android: true
  ios: true
  web:
    generate: true
    image_path: "assets/visual_identity/logo.PNG"
    background_color: "#ffffff"
  macos:
    generate: true
  windows:
    generate: true
 
flutter: 
  uses-material-design: true
 
  assets:
    - assets/visual_identity/logo.PNG
    - assets/lottie/auth/
    - assets/lottie/account/
    - assets/lottie/settings/
    - assets/lottie/

  fonts:
    - family: MenloRegular
      fonts:
        - asset: assets/font/Menlo-Regular-400.ttf
          weight: 100