name: mustachehub
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0' 
dependencies:
  flutter:
    sdk: flutter 
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  uuid: ^4.2.2
  freezed_annotation: ^2.4.1
  lottie: 2.7.0
  font_awesome_flutter: 10.6.0
  bloc: ^8.1.2 
  flutter_bloc: ^8.1.3
  replay_bloc: 0.2.5
  hydrated_bloc: ^9.1.3 
  go_router: 13.0.1
  media_query_core:
    path: packages/media_query_core
  mustache_hub_core:
    path: packages/mustache_hub_core
  commom_states:
    path: packages/commom_states

  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"
  build_runner: ^2.3.3 
  freezed: ^2.3.2

flutter_launcher_icons:
  image_path: "assets/visual_identity/raw_logo.PNG"
  android: true
  ios: true
  web:
    generate: true
    image_path: "assets/visual_identity/logo.PNG"
    background_color: "#ffffff"
  macos:
    generate: true
  windows:
    generate: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/visual_identity/logo.PNG
    - assets/lottie/
    - assets/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
