name: mustachehub
description: "A easy, logic-less text template viewer/builder."
publish_to: 'none'

version: 1.2.0+1

dependency_overrides: 
  uuid: ^4.3.3

  firebase_analytics: ^11.3.0
  firebase_remote_config: ^5.1.0
  firebase_core: ^3.4.0
  firebase_storage: ^12.2.0
  firebase_storage_web: ^3.9.13
  cloud_firestore: ^5.3.0
  cloud_firestore_web: ^4.1.2
  firebase_crashlytics: ^4.1.0
  firebase_messaging: ^15.1.0

  scrollable_positioned_list: ^0.3.8
  meta: 1.15.0
  test_api: ^0.7.3
  cupertino_icons: ^1.0.8
  equatable: ^2.0.5
  freezed_annotation: ^2.4.4
  animated_tree_view: ^2.2.0
  lottie: ^3.1.2
  font_awesome_flutter: ^10.7.0
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  replay_bloc: ^0.2.7
  enchanted_regex: ^1.0.7
  json_annotation: ^4.9.0
  hydrated_bloc: ^9.1.5
  go_router: ^14.2.1
  google_fonts: ^6.2.1
  enchanted_collection: ^1.3.0
  simple_platform: ^1.0.1
  image_network: ^2.5.6
  image_picker: ^1.1.2
  image_picker_for_web: ^3.0.4
  flutter_animate: ^4.5.0
  url_launcher: ^6.3.0
  fluttertoast: ^8.2.6
  dart_debouncer: ^1.1.0
  dotted_border: ^2.1.0
  cursor_autocomplete_options: ^2.0.0
  path_provider: ^2.1.3
  flex_color_scheme: ^7.3.1
  collection: ^1.19.0
  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.13.1"
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  freezed: ^2.5.7
  test: ^1.25.8
  lints: ^4.0.0
  package_info_plus: ^8.0.2
  material_symbols_icons:

  mustachex: 
    path: cloned_apis/mustachex  

environment:
  sdk: '>=3.4.4 <4.0.0'
  
dependencies:
  flutter:
    sdk: flutter 
  text_analyser: 
    path: packages/text_analyser
  package_info_plus:
  firebase_auth:
  cupertino_icons:
  equatable:
  scrollable_positioned_list:
  uuid:
  freezed_annotation:
  animated_tree_view:
  lottie:
  font_awesome_flutter:
  bloc:
  flutter_bloc:
  replay_bloc:
  material_symbols_icons:
  enchanted_regex:
  hydrated_bloc:
  go_router:
  google_fonts:
  enchanted_collection:
  simple_platform:
  image_network:
  image_picker:
  image_picker_for_web:
  flutter_animate:
  url_launcher:
  fluttertoast:
  dart_debouncer:
  dotted_border:
  cursor_autocomplete_options:
  path_provider:
  flex_color_scheme:
  collection:
  media_query_core:
    path: packages/media_query_core
  commom_source:
    path: packages/commom_source
  mustache_hub_core:
    path: packages/mustache_hub_core
  commom_states:
    path: packages/commom_states

  # Fork api's
  mustachex:
  mason: 
    path: cloned_apis/mason
 
  firebase_analytics: ^11.3.0
  firebase_remote_config: ^5.1.0
  firebase_core: ^3.4.0
  firebase_storage: ^12.2.0
  firebase_storage_web: ^3.9.13
  cloud_firestore: ^5.3.0
  cloud_firestore_web: ^4.1.2
  firebase_crashlytics: ^4.1.0
  firebase_messaging: ^15.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  flutter_launcher_icons:
  build_runner:
  json_serializable:
  freezed:

flutter_launcher_icons:
  image_path: "assets/visual_identity/raw_logo.PNG"
  android: true
  ios: true
  web:
    generate: true
    image_path: "assets/visual_identity/logo.PNG"
    background_color: "#ffffff"
  macos:
    generate: true
  windows:
    generate: true
 
flutter: 
  uses-material-design: true
 
  assets:
    - assets/visual_identity/logo.PNG
    - assets/lottie/auth/
    - assets/lottie/account/
    - assets/lottie/settings/
    - assets/lottie/

  fonts:
    - family: MenloRegular
      fonts:
        - asset: assets/font/Menlo-Regular-400.ttf
          weight: 100