name: mustache_hub_core
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.2.3
 
dependencies:
  equatable: ^2.0.5
  uuid: ^4.2.2
  freezed_annotation: ^2.4.1
  mason: 

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
  build_runner: ^2.3.3 
  freezed: ^2.3.2
