name: mustache_hub_core
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.2.3
 
dependencies:
  equatable:
  collection:
  uuid:
  json_annotation:
  freezed_annotation:
  mason:
    path: ../../cloned_apis/mason

dev_dependencies:
  lints:
  test:
  json_serializable:
  build_runner:
  freezed:
