name: commom_states
description: "A new Flutter package project."
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependency_overrides:
  meta: ^1.1.0

dependencies:
  flutter:
    sdk: flutter
  equatable:
  uuid:
  freezed_annotation:
  bloc:
  flutter_bloc:
  mustache_hub_core:
    path: ../mustache_hub_core
  micro_navigation_core:
    path: ../micro_navigation_core
  commom_source:
    path: ../commom_source
  hydrated_bloc:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 
  build_runner:
  json_serializable:
  freezed:

flutter: