name: mustachex
description: A starting point for Dart libraries or applications.
version: 1.0.0 

environment:
  sdk: ^3.2.0
 
dependencies: 
  mustache_recase: '>=2.4.0 <4.0.0'
  path: ^1.8.0
  quiver: ^3.0.1
  recase: ^4.0.0
  collection: ^1.16.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
