name: mason
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ^3.2.0
  
dependencies: 
  archive: ^3.1.11
  checked_yaml: ^2.0.1
  collection: ^1.15.0
  convert: ^3.1.0
  crypto: ^3.0.1
  http: '>=0.13.3 <2.0.0'
  json_annotation: ^4.8.1
  meta: ^1.7.0
  mustache_template: ^2.0.0
  path: ^1.8.0
  pool: ^1.5.1
  pub_semver: ^2.1.0
  yaml: ^3.1.0 

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
