name: text_analyser
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.2.3

dependency_overrides: 
  uuid: ^4.3.3
  mustachex: 
    path: ../../cloned_apis/mustachex  
  enchanted_collection:

# Add regular dependencies here.
dependencies:
  enchanted_regex:
  freezed_annotation:
  enchanted_collection:
  collection:
  mustache_hub_core:
    path: ../mustache_hub_core
  mustachex:
    path: ../../cloned_apis/mustachex
  mason:
    path: ../../cloned_apis/mason

dev_dependencies:
  lints:
  test:
  build_runner:
  freezed:
  json_serializable:
