name: text_analyser
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.2.3

dependency_overrides: 
  uuid: ^4.3.3
  mustachex: 
    path: ../../cloned_apis/mustachex  
  enchanted_collection: 1.3.0 

# Add regular dependencies here.
dependencies:
  enchanted_regex: ^1.0.7
  freezed_annotation: ^2.4.1 
  enchanted_collection: 1.3.0
  collection:
  mustache_hub_core:
    path: ../mustache_hub_core
  mustachex:
    path: ../../cloned_apis/mustachex
  mason:
    path: ../../cloned_apis/mason

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
  build_runner: ^2.3.3 
  freezed: ^2.3.2
  json_serializable: ^6.7.1
